# Generated by Django 2.2.13 on 2020-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('describe', models.TextField()),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
