# Generated by Django 2.2.13 on 2020-06-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
